//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tridion.Extensions.DynamicDelivery.Mvc.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Binaries
    {
        public string ComponentUri { get; set; }
        public string Path { get; set; }
        public byte[] Content { get; set; }
        public System.DateTime LastPublishedDate { get; set; }
    }
}
